# Generated by Django 6.0.3 on 2026-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlead',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='call_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='page_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='preferred_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='referrer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
