# Generated by Django 6.0.3 on 2026-09-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatlead_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlead',
            name='do_not_call',
            field=models.BooleanField(default=False),
        ),
    ]
