# Generated by Django 6.0.3 on 2026-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatlead_do_not_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlead',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
    ]
